### ISSUE TITLE
Extension eats up all the cpu, memory and swap

### ISSUE THREAD

**Issue by zurp** [pranaygp/vscode-css-peek#41] opened 2018-08-09 19:27 UTC
When opening a large project, this extension crashes multiple linux systems.
First it eats up all the CPU, then the memory, then the swap.

**Comment by lutzenburg** [comment] 2018-08-13 08:38
I just updated to 2.1.0 today on my Ubuntu 18.04 machine and watched as it ate up my memory and swap within seconds ultimately rendering my system unresponsive. 

In all fairness this was on a large project, however, before this update it didn't have any issues.

**Comment by arsari** [comment] 2018-11-22 16:40
Same problem in windows 10 with vs code v1.29. I have to disable the extension so my vs code doesn't crash.

**Comment by pranaygp** [comment] 2020-07-27 23:05
Is this still an issue on the latest VSCode and CSS Peek (3.3.0+)?

**Comment by guppy42** [comment] 2022-07-05 11:54
> Is this still an issue on the latest VSCode and CSS Peek (3.3.0+)?

Had to disable it today (v4.2.0) as it nearly took down a remote server, by spawning 10 processes that combined used 539,7% cpu and 51% memory.

clearly something isn't working as intended.

And yes it's a large codebase but intelephense can parse it just fine with out killing the server

**Comment by pranaygp** [comment] 2023-07-07 08:56
This has been fixed in version v4.3.4

**Closed by pranaygp** 2023-07-07 08:56 UTC
