### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by MuhammadHamzaAmir** [pranaygp/vscode-css-peek#99] opened 2020-12-21 15:36 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-css-peek`
- Extension Version: `4.0.2`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\HAMZA-~1\AppData\Local\Temp\pranaygp.vscode-css-peek-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-l
[pranaygp.vscode-css-peek-unresponsive.cpuprofile.txt](https://github.com/pranaygp/vscode-css-peek/files/5725156/pranaygp.vscode-css-peek-unresponsive.cpuprofile.txt)
oad

**Comment by pranaygp** [comment] 2020-12-21 18:13
Duplicate of #41

**Closed** 2020-12-21 18:13 UTC
