### ISSUE TITLE
No definition found for 'test'

### ISSUE THREAD

**Issue by emeydoubletee** [pranaygp/vscode-css-peek#16] opened 2017-12-17 23:21 UTC
**System**
OS: Linux
VS Code version: 1.19.0
CSS Peek version: 2.0.2

&nbsp;

**Issue**
When `Shift`+`F12` is pressed, the actual code it should refer to is not shown, which, in this example is:

```css
.test {
  color: green;
}
```

&nbsp;

**Other information**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33206161/34084852-8230ec90-e344-11e7-98e9-8f0cff1a3845.gif)

**Comment by pranaygp** [comment] 2017-12-18 00:21
@emeydoubletee I would need a little more information for this.

Most importantly, what does your project directory structure look like? The extensions *currently* doesn't work with css styling within the HTML file, so you need to have an independent .css file somewhere in the same workspace as the HTML file for it to work.

I can't tell from your gif how the styling is done

**Comment by emeydoubletee** [comment] 2017-12-18 00:29
I'm using an external CSS file.

Here's the tree:
```
.
├── assets
├── Changelog.md
├── css
│   └── master.css
├── index.html
├── js
├── License
├── Readme.md
├── repo-img
├── Roadmap.md
```

**Comment by pranaygp** [comment] 2017-12-18 00:41
I replicated your setup and it seems to work for me:

![image](https://user-images.githubusercontent.com/1797812/34085643-5c1d0af6-e359-11e7-9072-6a2334a24cd2.png)


I can't think of why it wouldn't work on Linux, but that could potentially be the issue?

Can you try opening the Output console in vs code, set the stream to "css-peek", try the peek again (like from your demo) and send me the output. here's an example of me doing it (an example where it works)

![image](https://user-images.githubusercontent.com/1797812/34085693-ee7b4e62-e359-11e7-9a87-9750378b7ef7.png)

**Comment by emeydoubletee** [comment] 2017-12-18 02:16
I created a different directory and the extension works **except** after adding a few lines in the HTML header.

**Test directory**

```
.
├── css
│   └── master.css
└── index.html

1 directory, 2 files
```

**Demo**
![normal](https://user-images.githubusercontent.com/33206161/34086706-5839c684-e35b-11e7-967c-1a146e90ef5f.gif)

&nbsp;

**Issue**

When I add the HTML lines below in the `header`,

```html
  <meta name="keywords" content="test">
  <meta name="description" content="test">
  <meta name="author" content="test">
```

- The output says `Invalid Selector...`.
- It says `No definition for test`.
- The default keyboard shortcuts for _Peak_, _Go To_, and _Hover_ no longer work.



I'm using the same directory and the same external CSS. The only changes are within the HTML file itself.

**Demo**
![issue](https://user-images.githubusercontent.com/33206161/34087172-7d8d255e-e35e-11e7-9554-13362a3df960.gif)

**Comment by pranaygp** [comment] 2017-12-18 02:50
Closing this as a duplicate of #14

**Closed by pranaygp** 2017-12-18 02:50 UTC
