### ISSUE TITLE
Output Panel constantly pops up with error when accessing files

### ISSUE THREAD

**Issue by tschofen** [pranaygp/vscode-css-peek#29] opened 2018-03-24 23:10 UTC
Issue Type: <b>Bug</b>

Whenever I open quickselect to open a file (cmd-T), the output panel pops up -- with css-peek selected in the popup menu -- with the following error:

`file:///Users/xxxx/dev/Tally/twa-bundle-base/node_modules/bootstrap/less/mixins/text-emphasis.less`
Found 14 symbols in file:///Users/xxxx/dev/Tally/twa-bundle-base/node_modules/bootstrap/less/mixins/table-row.less
[Error - 18:06:33] Request workspace/symbol failed.
  Message: Request workspace/symbol failed with message: Cannot read property 'offset' of null
  Code: -32603 
`
The only extension I'm running is CSS PEEK. Is there any way I can stop the output panel from opening up? On a small screen it's especially annoying.

I have a variety of workspaces that I use and all show the same issue.

VS Code version: Code 1.21.1 (79b44aa704ce542d8ca4a3cc44cfca566e7720f1, 2018-03-14T14:39:09.335Z)
OS version: Darwin x64 17.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|/Applications/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-peek|pra|2.1.0

</details>
Reproduces only with extensions

**Comment by pranaygp** [comment] 2018-03-25 19:03
I'm unable to reproduce this error @tschofen. I've set up a tiny test project and ran `npm install bootstrap@3.3.7`. When searching for a CSS classname, I get:
```
Found 14 symbols in file:///Users/pranaygp/github/vscode-css-peek/client/test/test_files/node_modules/bootstrap/less/mixins/table-row.less
```
but nothing after. I *don't* have the following error with:
```
Message: Request workspace/symbol failed with message: Cannot read property 'offset' of null
Code: -32603
```

Can you perhaps send me a github link to your project setup so I can clone it locally and reproduce the error?

**Comment by pranaygp** [comment] 2018-03-25 19:04
Also, this seems similar to #19 so I'm closing this

**Closed by pranaygp** 2018-03-25 19:04 UTC
Labels: duplicate
